// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goomgvikwwzksjkuriom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvb21ndmlrd3d6a3Nqa3VyaW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTM3MzgsImV4cCI6MjA1ODM4OTczOH0.fw3GRlTb3Ly75tG3AwPKSBNJ6ggaY-koJ6ZQK7KxO7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);